name: "Update metadata"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

permissions:
  contents: write
jobs:
  update-members:
    name: "Update members.json"
    runs-on: ubuntu-latest
    if: github.repository == 'hibernate/.github'
    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      with:
        fetch-depth: 1
    - name: Configure for commits
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'admin@hibernate.org'
    - run: ./scripts/update-members.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_METADATA_UPDATE }}
    - name: Push changes if any
      run: |
        git add -A
        git commit -m "Update members.json" || true
        git push